import React from "react";
import { LogoFrame } from "@/components/LogoFrame";
import { EventCard } from "@/components/EventCard";

export const TimeRoad: React.FC = () => {
  return (
    <svg width={1920} height={911}>
      <svg y={256}>
        <g name="first connection">
          <g className="translate-y-[1px]">
            <line
              x1={0}
              x2={124}
              y1={0}
              y2={0}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={0}
              x2={120}
              y1={4}
              y2={4}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={0}
              x2={116}
              y1={8}
              y2={8}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={0}
              x2={112}
              y1={12}
              y2={12}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={124}
              x2={168}
              y1={0}
              y2={50}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={120}
              x2={164}
              y1={4}
              y2={54}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={116}
              x2={160}
              y1={8}
              y2={58}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={112}
              x2={156}
              y1={12}
              y2={62}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={168}
              x2={268}
              y1={50}
              y2={50}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={164}
              x2={268}
              y1={54}
              y2={54}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={160}
              x2={268}
              y1={58}
              y2={58}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={156}
              x2={268}
              y1={62}
              y2={62}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
        </g>
      </svg>
      <LogoFrame x={268} y={221} logoPath="TUMLogo.png" />
      <EventCard
        x={113}
        y={448}
        company="Technical University of Munich"
        timePeriod="10.2020-CURRENT"
        content={`During my Computer Science Bachelor's at the Technical University of Munich, i have mastered:
- Programming: Proficient in Java, Python, C, and more.
- Systems Knowledge: Deep understanding of operating systems, IT security, and low-level programming.
- Data Skills: Strong in SQL database management and data analysis with R.
- Networking: Knowledgeable in network protocols and security.
- Mathematics and Economics: Well-versed in discrete mathematics, probability, and economic principles.`}
      />
      <svg x={458} y={308}>
        <g name="second connection">
          <g className="translate-y-[1px]">
            <line
              x1={0}
              x2={112}
              y1={52}
              y2={52}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={0}
              x2={116}
              y1={56}
              y2={56}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={0}
              x2={120}
              y1={60}
              y2={60}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={0}
              x2={124}
              y1={64}
              y2={64}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className=" translate-y-[1px]">
            <line
              x1={112}
              x2={152}
              y1={52}
              y2={0}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={116}
              x2={156}
              y1={56}
              y2={4}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={120}
              x2={160}
              y1={60}
              y2={8}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={124}
              x2={164}
              y1={64}
              y2={12}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={152}
              x2={276}
              y1={0}
              y2={0}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={156}
              x2={272}
              y1={4}
              y2={4}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={160}
              x2={268}
              y1={8}
              y2={8}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={164}
              x2={264}
              y1={12}
              y2={12}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={276}
              x2={348}
              y1={0}
              y2={95}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={272}
              x2={344}
              y1={4}
              y2={99}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={268}
              x2={340}
              y1={8}
              y2={103}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={264}
              x2={336}
              y1={12}
              y2={107}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={348}
              x2={348}
              y1={95}
              y2={218}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={344}
              x2={344}
              y1={99}
              y2={222}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={340}
              x2={340}
              y1={103}
              y2={226}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={336}
              x2={336}
              y1={107}
              y2={230}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={348}
              x2={391}
              y1={218}
              y2={265}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={344}
              x2={387}
              y1={222}
              y2={269}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={340}
              x2={383}
              y1={226}
              y2={273}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={336}
              x2={379}
              y1={230}
              y2={277}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={391}
              x2={476}
              y1={265}
              y2={265}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={387}
              x2={476}
              y1={269}
              y2={269}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={383}
              x2={476}
              y1={273}
              y2={273}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={379}
              x2={476}
              y1={277}
              y2={277}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
        </g>
      </svg>
      <LogoFrame x={934} y={486} logoPath="BertrandtLogo.png" />
      <EventCard
        x={779}
        company="Bertrandt Group"
        timePeriod="08.2021-02.2022"
        content={`Position: Working Student in the area of App Development Infotainment / Entertainment.

As part of the "In-Car-App Telematik" project, my responsibilities included:
• Software development of an In-Car App in Javascript
• Feature development, design, unit testing
• Software development within the Scrum process

Skills: TypeScript · Node.js · npm · Jest · Jenkins`}
      />
      <svg x={1124} y={196.5}>
        <g name="third connection">
          <g className="translate-y-[1px]">
            <line
              x1={0}
              x2={112}
              y1={320}
              y2={320}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={0}
              x2={116}
              y1={324}
              y2={324}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={0}
              x2={120}
              y1={328}
              y2={328}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={0}
              x2={124}
              y1={332}
              y2={332}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={112}
              x2={174}
              y1={320}
              y2={242}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={116}
              x2={178}
              y1={324}
              y2={246}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={120}
              x2={182}
              y1={328}
              y2={250}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={124}
              x2={186}
              y1={332}
              y2={254}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={174}
              x2={174}
              y1={242}
              y2={78}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={178}
              x2={178}
              y1={246}
              y2={82}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={182}
              x2={182}
              y1={250}
              y2={86}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={186}
              x2={186}
              y1={254}
              y2={90}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={174}
              x2={233}
              y1={78}
              y2={0}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={178}
              x2={237}
              y1={82}
              y2={4}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={182}
              x2={241}
              y1={86}
              y2={8}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={186}
              x2={245}
              y1={92}
              y2={12}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
          <g className="translate-y-[1px]">
            <line
              x1={233}
              x2={389}
              y1={0}
              y2={0}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={237}
              x2={389}
              y1={4}
              y2={4}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={241}
              x2={389}
              y1={8}
              y2={8}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
            <line
              x1={245}
              x2={389}
              y1={12}
              y2={12}
              stroke="#ff00ee"
              strokeWidth="1,5px"
            />
          </g>
        </g>
      </svg>
      <LogoFrame x={1513} y={50} logoPath="TeslaLogo.jpg" />
      <EventCard
        x={1358}
        y={269}
        company="Tesla"
        timePeriod="10.2023-04.2024"
        content={`Position: Software Engineering Intern

• Collaboration with product managers and end-users in analyzing functional and non-functional business requirements
• Close collaboration with engineers and product managers in the development and implementation of efficient and scalable features
• Development, enhancement, and maintenance of core functionalities
• Influencing architectural decisions with a focus on security, scalability, and high performance - improving standards and practices to ensure the highest product quality
• Establishment of document structures/naming schemes and general information management

Skills:  TypeScript / Node.js / npm / Jest / Jenkins / Docker / MySQL / Prisma`}
        height={465}
      />
    </svg>
  );
};
